### PR TITLE
Updated all dependencies

### PR DESCRIPTION
**Pull request by Download**
Moved preact deps to 'dependencies' i.s.o. 'devDependencies'

### CODE REVIEW

**Comment by ooade** [comment]
IMO, I don't think preact and preact-compat should be added to dependencies. It will already be added by default since used in a preact app. WDYT?

**Comment by Download** [comment]
I think it doesn't matter if they are added by the project using `preact-side-effect`; they are runtime dependencies for this project and so they should be in `dependencies`. 

You cannot 'require('x')' in the code and not have `'x'` as a dependency. `devDependencies` is there for things like mocha, chai, sinon etc that are only used in tests.

**Comment by Download** [comment]
I do think, however that we can completely drop `preact-compat` as a dependency... and maybe even `preact` itself... working on that now, but that PR will depend on this one.

**Comment by Download** [comment]
Thanks and great that you are on the ball! It makes it much easier to create more than one PR if previous PRs get merged quickly. Prepare for a few more. The current PRs are mainly to set a base so we can make changes without risking breaking stuff (which is why I added more tests in the other PR).

**Pull request merged**
