### PR TITLE
Trim dependencies

### PR DESCRIPTION
**Pull request by Download**
(b.t.w. if you enable your repo for Travis, you get continuous integration results right here on the pull request. For now you can see the tests here: https://travis-ci.org/Download/preact-side-effect )

### CODE REVIEW

**Comment by Download** [comment]
Ah I see you already enabled Travis!

**Comment by Download** [comment]
This PR removes dependencies on:
* react
* react-dom
* react-addons-test-utils
* exenv
* isparta
* shallowequal
* preact-compat

It adds a dev dependency on:
* preact-render-to-string

**Comment by ooade** [comment]
This looks good :+1:

**Comment by Download** [comment]
Thanks for merging everything so quick! My project was not using preact-compat and I didn't want to include it for this lib.  :)

**Comment by ooade** [comment]
@Download No problem. It's already published, i guess we had the same plan(creating preact-helmet) but i've bin busy lately :smile:

**Comment by Download** [comment]
> i guess we had the same plan(creating preact-helmet) but i've bin busy lately 😄

Ha! Yes you are so right!

In fact...
https://github.com/Download/preact-helmet

Thanks for inviting me to collaborate! I'll return the favor for preact-helmet.

**Pull request merged**
